# Generated by Django 4.2.3 on 2025-10-18 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.SlugField(
                        help_text="Globally unique namespace for short URLs",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_namespaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="url_shortener.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkUploadTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("input_file", models.FileField(upload_to="bulk_uploads/input/", verbose_name="Input File")),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="bulk_uploads/output/", verbose_name="Output File"
                    ),
                ),
                ("total_urls", models.IntegerField(default=0, verbose_name="Total URLs")),
                ("processed_urls", models.IntegerField(default=0, verbose_name="Processed URLs")),
                ("failed_urls", models.IntegerField(default=0, verbose_name="Failed URLs")),
                ("error_log", models.TextField(blank=True, verbose_name="Error Log")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_upload_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_upload_tasks",
                        to="url_shortener.namespace",
                        verbose_name="Namespace",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_upload_tasks",
                        to="url_shortener.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Upload Task",
                "verbose_name_plural": "Bulk Upload Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "short_code",
                    models.SlugField(help_text="Unique code within the namespace", verbose_name="Short Code"),
                ),
                (
                    "original_url",
                    models.URLField(
                        max_length=2048,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Original URL",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("click_count", models.IntegerField(default=0, verbose_name="Click Count")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="URL will be invalid after this date",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Private URLs require JWT authentication to access",
                        verbose_name="Is Private",
                    ),
                ),
                ("qr_code", models.FileField(blank=True, null=True, upload_to="qr_codes/", verbose_name="QR Code")),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255, verbose_name="Tags"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_short_urls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_urls",
                        to="url_shortener.namespace",
                        verbose_name="Namespace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["namespace", "short_code"], name="url_shorten_namespa_bebdba_idx")],
                "unique_together": {("namespace", "short_code")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("EDITOR", "Editor"), ("VIEWER", "Viewer")],
                        default="VIEWER",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Joined At")),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="url_shortener.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("organization", "user")},
            },
        ),
    ]
