# Generated by Django 4.2.3 on 2025-10-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0002_alter_shorturl_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_code",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Unique code within the namespace. Leave blank to auto-generate.",
                verbose_name="Short Code",
            ),
        ),
    ]
