# Generated by Django 4.2.3 on 2025-10-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("url_shortener", "0003_alter_shorturl_short_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("EDITOR", "Editor"), ("VIEWER", "Viewer")],
                        default="VIEWER",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Token")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="Accepted At")),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_org_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="url_shortener.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Invitation",
                "verbose_name_plural": "Organization Invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email", "status"], name="url_shorten_email_9c34e8_idx"),
                    models.Index(fields=["token"], name="url_shorten_token_9713cc_idx"),
                ],
                "unique_together": {("organization", "email", "status")},
            },
        ),
    ]
